### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by hafiizh10** [akhwan90/cat#19]
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 347

Itu kenapa ya pak

**Comment by akhwan90** [comment]
@hafiizh10  : setting databasenya belum benar, gan.. simak caranya berikut ini : http://nur-akhwan.blogspot.co.id/2016/01/langkah-langkah-install-aplikasi-ujian.html
