### ISSUE TITLE
Mohon penjelasan tabel m_admin dan tabel tr_ikut_ujian

### ISSUE THREAD

**Issue by satyakresna** [akhwan90/cat#34]
Halo mas Akhwan, trima kasih sudah menyediakan source code CAT ini. Saya ingin bertanya maksud dari kolom `kon_id` pada tabel m_admin dan kolom `status` pada tabel tr_ikut_ujian. Saya mohon penjelasannya.

**Comment by akhwan90** [comment]
Halo, gan..

kon_id pada tabel m_admin berfungsi sebagai konektor dengan tabel master.. jadi gini : di m_admin ada field level, dan kon_id, nah, kalo misalnya level-nya siswa, makan value kon_id merupakan id siswa pada tabel m_siswa, begitu juga kalo level-nya guru, maka value kon_id merupakan id guru pada tabel m_guru.. hehe

terus kolom status pada tabel tr_ikut_ujian, merupakan flag untuk menandai bahwa ia sudah selesai mengikuti ujian (dgn menekan tombol "selesai ujian"). itu, gan..
