### ISSUE TITLE
input karakter di word tidak kebaca

### ISSUE THREAD

**Issue by dibsiss** [akhwan90/cat#40]
selamat sore mas, sebelumnya terimakasih telah share aplikasi cat
dan sangat berguna bagi saya untuk reverensi,
ada yang mau saya tanyakan, ketika saya input karakter spesial dari microsoft word, kog ke baca ? di databasenya, mohon saran dan bimbingannya,terimakasih

**Comment by akhwan90** [comment]
contohnya pegimana, gan, karakter spesial..? simbol simbolkah..?

**Comment by dibsiss** [comment]
iya mas karakter spesial dan simbol simbol kayak gini mas !$⅛⅞⁄√∑≤≥≥∫ yang kemarin jadi tanda tanya
ketika di input, apakah ada salah setting mas
terimakasih

**Comment by akhwan90** [comment]
hehe.. belum support simbol2 khusus.. baru bisa support karakter yang ada di keyboard..
