### ISSUE TITLE
MAPEL tidak bisa dihapus pada cat_dua

### ISSUE THREAD

**Issue by hydodie** [akhwan90/cat#41]
MAPEL tidak bisa dihapus pada cat_dua

**Comment by akhwan90** [comment]
disitu ada trigger query mysql, kebetulan tabel mapel jadi parrent, .
jadi klo mau hapus parent nya harus hapus child, nya..
hehe

#cmiiw

**Comment by hydodie** [comment]
tesu kok jawaban cuma sampe D aja yah?
di upload soalnya sampe E opsinya

**Comment by akhwan90** [comment]
file config.php, isian "jml_opsi" dibikin 5
