### ISSUE TITLE
Soalnya gak muncul di Siswa

### ISSUE THREAD

**Issue by agyana** [akhwan90/cat#43]
Mohon bantuannya, Saat siswa login soal ujiannya gak muncul.

**Comment by akhwan90** [comment]
harus pilih ujian dulu, masukin token, baru kemudian bisa mengikuti ujian

**Comment by agyana** [comment]
Terima kasih banyak, di localhost sdh ok, tapi waktu saya jalankan di webhosting data-datanya gak muncul dan waktu input data siswa atau yang lainnya pun gak muncul. Mohon bantuannya, terima kasih.

**Comment by akhwan90** [comment]
cb upload versi terbaru.. 
https://github.com/akhwan90/cat/releases/tag/2.2
