### ISSUE TITLE
Undefined index : import_excel saat akan import soal, siswa, guru.

### ISSUE THREAD

**Issue by agetoz** [akhwan90/cat#44]

**Comment by akhwan90** [comment]
coba download lagi aplikasinya, gan..

**Comment by agetoz** [comment]
Error Number: 1364

Field 'opsi_a' doesn't have a default value

INSERT INTO `m_soal` (`id_guru`, `id_mapel`, `bobot`, `soal`, `jawaban`) VALUES ('6', '2', '1', '

asdasdasd

\n', 'A')
Filename: /var/www/catv2/controllers/adm.php

Line Number: 536

**Comment by akhwan90** [comment]
download versi terbaru ... 
https://github.com/akhwan90/cat/releases/tag/2.2
