### ISSUE TITLE
soal tidak masuk kedatabase

### ISSUE THREAD

**Issue by MolitaHasan** [akhwan90/cat#46]
saya ingin menggabungkan CAT versi 1 dan 2, di cat versi 2 saya ambil bagian siswa, guru dan mapel, sedangkan yang versi 1 saya ambil m_soal. tp sudah dicoba berkali-kali, soal yang diinput tidak mau tersimpan didatabase, padahal tidak ada error dan syntak controllernya jga sudah benar.
kira-kira kenapa ya?

**Comment by akhwan90** [comment]
yg versi 1 itu untuk m_soal pake ajax, yang versi 2, nggak pake ajax.. coba dicek, post ajax-nya..

**Comment by MolitaHasan** [comment]
post ajaxnya di aplikasi.js kan? sudah dibuat sperti versi 1, tapi tetap tidak bisa gan. AjaxFileUpload.js jga sudah saya pindahkan ke versi terbaru
