### ISSUE TITLE
sisipkan gambar

### ISSUE THREAD

**Issue by ahmadakmaludin** [akhwan90/cat#47]
gan mau tanya kalo sisipkan gambar di soal itu gimana ya? udah taro di file htdocsnya udah copy pathnya tappi di preview ga keluar apalagi disoalnya juga gakeluar

**Comment by ahmadakmaludin** [comment]
sebelumya terimakasih banyak atas aplikasinya

**Comment by akhwan90** [comment]
untuk penyisipan gambar, itu biar mudah harus lewat online, gan.. 
jadi gambar diupload, kemudian url-nya nanti disisipkan pas membuat soal itu, 
dan juga pas ujian juga harus online.. hehe

klo mau lebih aman lagi, lewat file upload di soalnya..

**Comment by ahmadakmaludin** [comment]
jadi kalo offline emang ga bisa ya gan? soalnya ane pakenya offline

**Comment by ahmadakmaludin** [comment]
gan ane udah hosting, tapi ga bisa loggin, checking terus itu kenapa ya?

**Comment by akhwan90** [comment]
masih ada kelasahan.. cek semangatnya.. :D
