### ISSUE TITLE
Muncul Error id_mapel

### ISSUE THREAD

**Issue by agyana** [akhwan90/cat#50]
A PHP Error was encountered
Severity: Notice
Message: Undefined variable: id_mapel
Filename: controllers/adm.php
Line Number: 624

A PHP Error was encountered
Severity: Warning
Message: Cannot modify header information - headers already sent by (output started at /system/core/Exceptions.php:185)
Filename: helpers/url_helper.php
Line Number: 543

Mohon pencerahannya, terima kasih atas bantuannya.

**Comment by akhwan90** [comment]
download versi terbaru : https://github.com/akhwan90/cat/releases/tag/2.2
