### ISSUE TITLE
Baris Baru untuk soal yang di Import dari excel

### ISSUE THREAD

**Issue by agusksaid** [akhwan90/cat#53]
file adm.php
line 1348
`$soalok = '';`

line 1354
```
$soalok = preg_replace("/\r?\n|\r/", "<p>$1</p>", $d->soal);
$html .= '<p>' .$soalok. '</p><p>'.$tampil_media.'</p><div class="funkyradio">';
 //$html .= '<p>'.$d->soal.'</p><p>'.$tampil_media.'</p><div class="funkyradio">';
```

**Comment by akhwan90** [comment]
mungkin bisa disertakan update untuk apa, ya, gan @agusksaid .. 

(ane belum paham fungsi preg_replace, ini.. wkwkk)

**Comment by agusksaid** [comment]
Soalkan tidk semuanya 1 baris. Klu di ketik langsung d CAT tdk ada masalah. 
Tapi klu yg d import dr excel maka akan jadi 1 baris semua. Walaupun yg di excel itu ada baris barunya. Klu di excel alt+enter untul membuat baris baru dlm 1 row. 
Fungsi itu untuk merubah baris baru yg dr excel menjadi baris baru d web.

**Comment by akhwan90** [comment]
o, ya, gan.. oke, ilmu baru buat ane, thanks gan...
