### ISSUE TITLE
Upload gambar tersedia, tapi....

### ISSUE THREAD

**Issue by suhardiyan** [akhwan90/cat#55]
Di create soal tersedia upload gambar, tetapi bagaimana cara menggunakannya ? saya coba sudah sukses tapi munculnya dimana ? thanks

**Comment by akhwan90** [comment]
ada keterangan error upload gambar, kah..?

**Comment by suhardiyan** [comment]
Case resolved mas, versi PHP dan mysql saya terlalu update haha
