### ISSUE TITLE
DataTables error saat memasukan parameter sorting.

### ISSUE THREAD

**Issue by bin-tanggerang** [akhwan90/cat#58]
halo mas, terimakasih sebelumnya, aplikasi ini sangat membantu sekali bagi saya terimakasih mas. oiya, ini pas saya masukin parameter sorting di function datatables, ko malah eror ya mas? saya harus cek dibagian file yang mana ya mas? tolong dibantu ya :) :+1: :1st_place_medal:

**Comment by akhwan90** [comment]
hallo, gan..
kalo make sorting otomatis ada perubahan di SQL query datatables nya gan. dan coba dibaca docs-nya Datatables

**Comment by bin-tanggerang** [comment]
query yang mananya ya mas? saya masih pemula hehe.. pas saya inspect ketika sorting, file urutan ajaxnya tetep sama aja mas. gimana itu mas?

**Comment by bin-tanggerang** [comment]
pake yang inikah mas? https://editor.datatables.net/examples/simple/join.html

**Comment by akhwan90** [comment]
coba di-enable di config pagination nya.. terus juga nanti di ajax datatables-nya jg diubah, ada query untuk sorting by apa, ..

https://datatables.net/examples/basic_init/table_sorting.html

**Comment by bin-tanggerang** [comment]
oke tq mas, bermanfaat sekali ilmunya
