### ISSUE TITLE
UNTUK SETTING PENENTUAN WAKTU, TOKEN, JUMLAH SOAL DIMANA GAN???

### ISSUE THREAD

**Issue by irawan18** [akhwan90/cat#59]
Salam NEWBIE GAN.

numpang gabung gan. untuk setting ujian serta penentuan token bagaimana gan karena setelah saya coba hanya import dan tambah data saja yang tersedia

Mohon Pemcerahannya

**Comment by akhwan90** [comment]
masuk lewat level guru, kemudian buat soal, kalo soal sudah mencukupi kemudian buat ujian.. nah pas waktu buat ujian itu, bisa ditentuikan waktu, toke, dan jumlah soalnya..
