### ISSUE TITLE
Error A PHP

### ISSUE THREAD

**Issue by ensputra** [akhwan90/cat#61]
Tolong bantuannya :+1: 
**A PHP Error was encountered**
Severity: Notice
Message: Undefined property: CI_DB_mysqli_driver::$db_cat
Filename: database/DB_driver.php
Line Number: 123

**A PHP Error was encountered**
Severity: Notice
Message: Undefined property: CI_DB_mysqli_driver::$db_cat
Filename: database/DB_driver.php
Line Number: 123

**A PHP Error was encountered**
Severity: Notice
Message: Undefined property: CI_DB_mysqli_driver::$db_cat
Filename: database/DB_driver.php
Line Number: 123

**A PHP Error was encountered**
Severity: Notice
Message: Undefined index: waktu
Filename: controllers/adm.php
Line Number: 8

**Comment by akhwan90** [comment]
coba driver diubah dari mysql ke mysqli
