### ISSUE TITLE
CAT 2.0 : A Database Error Occurred.  Error Number: 1364

### ISSUE THREAD

**Issue by editanka** [akhwan90/cat#65]
Saya baru mencoba CAT 2.0. Download langsung dari GitHub.
Saya install di localhost.
Sewaktu saya selesai meng-input soal, lalu meng-klik tombol simpan, muncul error sebagai berikut:

A Database Error Occurred

Error Number: 1364

Field 'file' doesn't have a default value

INSERT INTO `m_soal` (`id_guru`, `id_mapel`, `bobot`, `soal`, `jawaban`) VALUES ('8', '5', '1', '

Berkut adaah contoh bahasa pemrograman, kecuali :

\r\n', 'D')
Filename: D:\wamp64\www\cat\system\database\DB_driver.php

Line Number: 331

**Comment by akhwan90** [comment]
coba buka phpmyadmin, pilih database db_cat_dua, pilih "SQL", trus copy pastekan skrip di bawah ini ke isian SQL :

ALTER TABLE m_soal
CHANGE COLUMN file file VARCHAR(150) NULL DEFAULT NULL AFTER bobot;
