### ISSUE TITLE
soal tidak bisa lebih saat membuat ujian.. 

### ISSUE THREAD

**Issue by airlandz** [akhwan90/cat#67]
slamat pagi mastah nur akhwan. 
untuk program catnya, apabila saya mempunyai soal 50. dan saya akan membuat ujian hanya 40 soal itu nggak bisa, 
kalo mau buat ujian harus sama dengan jumlah soal. saya mau terdapt bank soal,. jadi bukan hanya mengacak nomor soal. tapi juga mengacak soal. jadi soalnya persiswa berfariasi.
terimakasih.

**Comment by akhwan90** [comment]
pagi gan.. bisa jadi memang soalnya belum cukup, kalo dibuat 40.. 
coba setelah pilih mapel itu, tunggu beberapa detik (kalau sudah dionlinekan, jg tergantung jaringan) sampai bisa..
untuk pengacakan memang hanya baru bisa mengacak nomer soal..
