### ISSUE TITLE
penambahan soal error

### ISSUE THREAD

**Issue by koplaxx** [akhwan90/cat#68]
mas penambahan soale jih error solusie piye iki ??

Error Number: 1364

Field 'file' doesn't have a default value

INSERT INTO `m_soal` (`id_guru`, `id_mapel`, `bobot`, `soal`, `jawaban`) VALUES ('6', '1', '1', '

test
\r\n', 'A')

Filename: C:\wamp64\www\cat\system\database\DB_driver.php

Line Number: 331

**Comment by akhwan90** [comment]
coba buka phpmyadmin, pilih database db_cat_dua, pilih "SQL", trus copy pastekan skrip di bawah ini ke isian SQL :  

ALTER TABLE `m_soal`
	CHANGE COLUMN `file` `file` VARCHAR(150) NULL DEFAULT NULL AFTER `bobot`;
