### ISSUE TITLE
Tombol Ragu-ragu tidak jalan

### ISSUE THREAD

**Issue by freylast** [akhwan90/cat#69]
maaf, untuk update tombol ragu-ragu kenapa tidak jalan dengan semestinya.
tiap di klik tombol ragu-ragu yang hilang jawabannya selalu soal nomor 1.
untuk ragu-ragu memang menghilangkan jawaban kah?
kalau unbk ragu-ragu soal kan tetap di jawab tetapi warna di navigasi jadi kuning.

**Comment by akhwan90** [comment]
https://github.com/akhwan90/cat/commit/34716d4ad787818e15160e7b82e71183c3ed505f
