### ISSUE TITLE
Bertanya apakah bisa diedit

### ISSUE THREAD

**Issue by kamalmstp** [akhwan90/cat#73]
Assalamualaikum, saya pengen bertanya.
Apakah aplikasi nya bisa di edit jadi seperti soal psikolog, dimana pilihan ganda nya ada A, B, dan C, masing2 pilihan ganda memiliki nilainya masing2, misalkan A mempunyai nilai 2, B memiliki nilai 0, dan C memiliki nilai 1, dengan kata lain semua pilihan ganda ada nilainya masing2. Mohon bantuannya

**Comment by akhwan90** [comment]
boleh gan, diedit.. silakan diedit... pastinya ada penambahan di database... :D

**Comment by kamalmstp** [comment]
gagal terus gan, banyak errornya ketika di edit
