### ISSUE TITLE
Undefined Offset: 1

### ISSUE THREAD

**Issue by dhistira** [akhwan90/cat#74]
Saya coba pake equation di text editornya. Awalnya ada masalah gabisa input soal, akhirnya saya ubah ke UTF8. Terus masalah lagi pas di sisi siswa, mengerjakan soal, opsi jawaban yang pakai equation tidak terbaca.

Error: Message: Undefined offset: 1
Filename: controllers/adm.php

**Comment by dhistira** [comment]
Ternyata problemnya pas awal sebelum saya ganti UTF8, value ke DB opsi a dst menjadi NULL. Makanya undefined offset. Terimakasih

**Comment by akhwan90** [comment]
Hehe, ok, gan.. 
sebagai tambahan aja, equation itu cara kerjanya (klo gak salah) : 
Generate gambar berdasarkan perintah di equation editor, kemudian disimpan di servernya equation editor. Sehingga kalau menggunakan soal yg pake equation Harus wajib ada koneksi Internet.. 

Terimakasih..hehe

**Comment by dhistira** [comment]
tambahan juga om, yang lain kalo mau pake equation, di kolom soal, opsi a-e, charsetnya diubah jadi UTF 8 biar ga null ehehehe
